### ISSUE TITLE
Module `react-native-module` does not exist in the Haste module map

### ISSUE THREAD

**Issue by rondinellimorais** [814k31/TestReactNativeNativeModule#1]
Hey man, how do you resolve this trouble?

```
// Importing here doesn't work
import RNModule from 'react-native-module';
```

**Comment by 814k31** [comment]
I had to package it in order to be used

https://github.com/facebook/react-native/issues/23327

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rondinellimorais** [comment]
Thank you! Looks like [Reat Native Metro](https://github.com/facebook/metro/issues/1) doens't work symlinks. I'm copy the library directory inside **node_modules** and it's work fine.
